import type { ChecklistCode, EventCode, ExplanationCode, NodeCode, Pattern } from '../domain'
export type Locale = 'en' | 'zh'
export type Theme = 'light' | 'dark' | 'system'
export const messages = {
  en: {
    title: 'Design the workflow. Test the failure.', subtitle: 'Turn constraints into an agent architecture you can explain.', export: 'Export plan', exported: 'Plan downloaded as Markdown.', exportFailed: 'The download could not start. Please try again.',
    constraints: 'Set constraints', blueprint: 'Your blueprint', stress: 'Stress test', reset: 'Reset', resetDone: 'Default settings restored.',
    taskShape: 'Task shape', fixed: 'Defined steps', fixedHelp: 'A clear sequence toward a known goal.', open: 'Open-ended', openHelp: 'The work needs to be broken down as it unfolds.',
    sideEffects: 'Side effects', none: 'Read only', noneHelp: 'No changes to external systems.', reversible: 'Reversible', reversibleHelp: 'Changes can be undone.', irreversible: 'Irreversible', irreversibleHelp: 'Changes cannot be easily undone.',
    retrieval: 'Use retrieval', retrievalHelp: 'Bring relevant source context into the workflow.', resumable: 'Resume after interruption', resumableHelp: 'Include a checkpoint in the proposed design.', parallel: 'Parallel work', parallelHelp: 'Assume two independent units of work.', maxRetries: 'Retry budget', retriesHelp: 'Additional attempts after the initial try. Reads and validation only.',
    connections: 'Connections', why: 'Why this structure', checklist: 'Before you ship', checklistHelp: 'Design guidance, not a production-readiness certification.', enabled: 'In design', recommended: 'Add in production', not_needed: 'Not needed here',
    simulation: 'Deterministic simulation', simulationHelp: 'Inject a persistent fault and inspect a reproducible trace. No model or external action runs.', fault: 'Inject a fault', noFault: 'No fault', timeout: 'Tool timeout', invalid_output: 'Invalid output', approval_denied: 'Approval denied', run: 'Run simulation', trace: 'Simulation trace', traceEmpty: 'Choose a fault, then run the simulation.', traceEmptyHelp: 'Follow each step, retry, and stop condition here.', completed: 'Completed', failed: 'Stopped safely', blocked: 'Approval blocked', attempt: 'Attempt', checkpoint: 'Simulated checkpoint available', changed: 'Blueprint updated. Run again to test the new design.',
    footer: 'A deterministic teaching model, not live LLM execution. Your settings stay in this browser.', how: 'How it works', sources: 'Sources', method: 'A small, explainable heuristic', methodText: 'Defined steps use a pipeline. Independent parallel work uses a fan-out workflow. Open-ended work uses an orchestration blueprint; production needs an explicit iteration budget. These are starting points, not a uniquely optimal architecture.', methodLimits: 'Timeouts and invalid outputs persist until the retry budget is exhausted. Validation and approval precede modeled side effects. Checkpoints here are illustrative: a real deployment needs durable storage, replay-safe steps, and explicit authorization.', parallelNote: 'Branches can run independently; the trace lists them in a stable order.', sourceNote: 'Primary references checked 1 October 2026. Our decision rules are a teaching simplification of these sources.',
    theme: 'Appearance', light: 'Light', dark: 'Dark', system: 'System', language: 'Language', savedInvalid: 'Saved settings were invalid. Safe defaults loaded.', storageUnavailable: 'Browser storage is unavailable. Changes work for this visit only.', settingsSaved: 'Saved in this browser', skip: 'Skip to workbench', node: 'Step', connector: 'Next step',
  },
  zh: {
    title: '设计工作流，检验失败路径。', subtitle: '把任务约束变成讲得清楚的智能体架构。', export: '导出方案', exported: '方案已下载为 Markdown 文件。', exportFailed: '下载未能开始，请重试。',
    constraints: '设置约束', blueprint: '架构蓝图', stress: '故障测试', reset: '重置', resetDone: '已恢复默认设置。',
    taskShape: '任务形式', fixed: '固定步骤', fixedHelp: '通过明确的步骤达成已知目标。', open: '开放任务', openHelp: '需要随着任务推进逐步拆解工作。',
    sideEffects: '外部操作', none: '只读', noneHelp: '不修改外部系统。', reversible: '可撤销', reversibleHelp: '操作造成的变更可以撤销。', irreversible: '难以撤销', irreversibleHelp: '操作造成的变更难以撤销。',
    retrieval: '使用检索', retrievalHelp: '在工作流中加入相关来源的上下文。', resumable: '支持中断后恢复', resumableHelp: '在建议方案中加入检查点。', parallel: '并行处理', parallelHelp: '假设有两个互不依赖的工作单元。', maxRetries: '重试上限', retriesHelp: '首次尝试之后的追加次数，仅用于读取和验证。',
    connections: '连接关系', why: '为什么这样设计', checklist: '上线前检查', checklistHelp: '这是设计建议，并非生产就绪认证。', enabled: '已纳入设计', recommended: '生产环境需补充', not_needed: '此处无需',
    simulation: '确定性模拟', simulationHelp: '注入持续故障，查看可复现的轨迹。不会运行模型或执行外部操作。', fault: '注入故障', noFault: '无故障', timeout: '工具超时', invalid_output: '输出不合规', approval_denied: '审批被拒绝', run: '运行模拟', trace: '模拟轨迹', traceEmpty: '选择故障，然后运行模拟。', traceEmptyHelp: '在这里查看每一步、重试与停止条件。', completed: '已完成', failed: '已安全停止', blocked: '审批已阻止后续操作', attempt: '尝试', checkpoint: '已有模拟检查点', changed: '蓝图已更新，请重新运行以测试新方案。',
    footer: '这是确定性教学模型，不会实际执行大语言模型。设置仅保存在当前浏览器。', how: '工作原理', sources: '参考来源', method: '简单、可解释的设计规则', methodText: '固定步骤使用流水线；互不依赖的并行任务使用分发工作流；开放任务使用编排蓝图，生产环境需要明确的迭代上限。这些方案是设计起点，并非唯一最优架构。', methodLimits: '超时和不合规输出会持续到重试额度耗尽。验证和审批位于模拟外部操作之前。此处的检查点仅用于说明；真实部署需要持久化存储、可安全重放的步骤和明确授权。', parallelNote: '分支可独立执行；轨迹按固定顺序显示。', sourceNote: '一手资料核对于 2026 年 10 月 1 日。本工具的规则是对这些资料的教学性简化。',
    theme: '外观', light: '浅色', dark: '深色', system: '跟随系统', language: '语言', savedInvalid: '已保存的设置无效，已加载安全默认值。', storageUnavailable: '浏览器存储不可用，修改仅在本次访问有效。', settingsSaved: '已保存到当前浏览器', skip: '跳转到工作台', node: '步骤', connector: '下一步',
  },
} as const
export const patterns: Record<Locale, Record<Pattern, string>> = {
  en: { pipeline: 'Sequential workflow', router: 'Parallel fan-out workflow', orchestrator: 'Orchestration blueprint' },
  zh: { pipeline: '顺序工作流', router: '并行分发工作流', orchestrator: '任务编排蓝图' },
}
export const nodeLabels: Record<Locale, Record<NodeCode, string>> = {
  en: { receive_input: 'Request', plan_bounded_work: 'Outline work', route_independent_work: 'Distribute work', retrieve_context: 'Retrieve context', perform_work: 'Execute step', perform_branch_a: 'Work branch A', perform_branch_b: 'Work branch B', validate_output: 'Validate output', save_checkpoint: 'Save checkpoint', require_approval: 'Human approval', perform_reversible_action: 'Reversible action', perform_irreversible_action: 'Irreversible action', return_output: 'Result' },
  zh: { receive_input: '接收请求', plan_bounded_work: '规划工作', route_independent_work: '分发独立任务', retrieve_context: '检索上下文', perform_work: '执行工作步骤', perform_branch_a: '工作分支 A', perform_branch_b: '工作分支 B', validate_output: '验证输出', save_checkpoint: '保存检查点', require_approval: '人工审批', perform_reversible_action: '可撤销操作', perform_irreversible_action: '难以撤销的操作', return_output: '返回结果' },
}
export const explanations: Record<Locale, Record<ExplanationCode, string>> = {
  en: { fixed_sequence: 'Defined steps favor a predictable workflow.', independent_branches: 'Independent work can fan out, then join before validation.', dynamic_decomposition: 'Open-ended work benefits from a planner with explicit bounds.', retrieve_before_work: 'Retrieve source context before the work begins.', validate_before_effects: 'Validate output before any external side effect.', approval_before_irreversible: 'Require human approval before hard-to-reverse actions.', checkpoint_before_effects: 'Checkpoint validated state before side effects.', bounded_retry_budget: 'Retry reads and validation within a fixed budget.', no_automatic_retries: 'With no retries, a fault stops the workflow immediately.', simulation_only: 'This is a deterministic design model, not an executing agent.' },
  zh: { fixed_sequence: '明确的步骤适合可预测的顺序工作流。', independent_branches: '独立任务可以并行展开，然后汇合验证。', dynamic_decomposition: '开放任务适合具有明确边界的规划器。', retrieve_before_work: '在工作开始前检索来源上下文。', validate_before_effects: '在产生任何外部变更之前验证输出。', approval_before_irreversible: '难以撤销的操作必须先经过人工审批。', checkpoint_before_effects: '在外部操作之前保存已验证状态的检查点。', bounded_retry_budget: '读取和验证只能在固定额度内重试。', no_automatic_retries: '没有重试额度时，故障会立即停止工作流。', simulation_only: '这是确定性设计模型，并非正在运行的智能体。' },
}
export const checklistLabels: Record<Locale, Record<ChecklistCode, string>> = {
  en: { input_contract: 'Define the input contract', output_validation: 'Validate tool outputs', bounded_retries: 'Bound retries', human_approval: 'Test rejected approvals', checkpointing: 'Use durable checkpoints', idempotent_actions: 'Make side effects replay-safe', tool_allowlist: 'Restrict available tools', observability: 'Record traces and outcomes', parallel_join: 'Join all branches', iteration_budget: 'Bound planner iterations', retrieval_provenance: 'Preserve source provenance' },
  zh: { input_contract: '定义输入契约', output_validation: '验证工具输出', bounded_retries: '限制重试次数', human_approval: '测试审批拒绝路径', checkpointing: '使用持久化检查点', idempotent_actions: '确保外部操作可安全重放', tool_allowlist: '限制可用工具', observability: '记录轨迹和结果', parallel_join: '汇合所有分支', iteration_budget: '限制规划器迭代次数', retrieval_provenance: '保留来源出处' },
}
export const eventLabels: Record<Locale, Record<EventCode, string>> = {
  en: { step_completed: 'Step completed', input_validated: 'Request accepted', plan_created: 'Plan step simulated', branches_routed: 'Independent work distributed', context_retrieved: 'Context retrieved', work_completed: 'Work completed', output_validated: 'Validation passed', checkpoint_saved: 'Checkpoint simulated', approval_granted_simulated: 'Approval granted (simulated)', action_simulated: 'External action simulated', output_returned: 'Result returned', timeout_retry: 'Tool timeout · retry scheduled', timeout_exhausted: 'Tool timeout · budget exhausted', invalid_output_retry: 'Invalid output · rework scheduled', invalid_output_exhausted: 'Invalid output · budget exhausted', approval_denied: 'Approval denied · action blocked', upstream_stopped: 'Skipped after upstream stop', fault_not_applicable: 'No approval gate in this design; fault not applied' },
  zh: { step_completed: '步骤已完成', input_validated: '请求已接收', plan_created: '已模拟规划步骤', branches_routed: '已分发独立任务', context_retrieved: '已检索上下文', work_completed: '工作已完成', output_validated: '验证通过', checkpoint_saved: '已模拟检查点', approval_granted_simulated: '审批通过（模拟）', action_simulated: '已模拟外部操作', output_returned: '已返回结果', timeout_retry: '工具超时 · 安排重试', timeout_exhausted: '工具超时 · 重试额度耗尽', invalid_output_retry: '输出不合规 · 安排重新执行', invalid_output_exhausted: '输出不合规 · 重试额度耗尽', approval_denied: '审批被拒绝 · 操作已阻止', upstream_stopped: '上游停止后跳过', fault_not_applicable: '此方案没有审批关卡，未应用该故障' },
}
export const sources = [
  { title: 'Anthropic · Building effective agents', url: 'https://www.anthropic.com/engineering/building-effective-agents' },
  { title: 'LangGraph · Persistence', url: 'https://docs.langchain.com/oss/javascript/langgraph/persistence' },
  { title: 'LangGraph · Interrupts', url: 'https://docs.langchain.com/oss/javascript/langgraph/interrupts' },
  { title: 'LangGraph · Fault tolerance', url: 'https://docs.langchain.com/oss/javascript/langgraph/fault-tolerance' },
  { title: 'OpenAI Agents SDK · Human in the loop', url: 'https://openai.github.io/openai-agents-python/human_in_the_loop/' },
] as const
