import { mount } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { nextTick } from 'vue'
import App from '../../src/App.vue'
import AppIcon from '../../src/components/AppIcon.vue'
import { DEFAULT_INPUT, serializeLabInput } from '../../src/domain'
import { INPUT_KEY, PREFS_KEY } from '../../src/ui/storage'
import { useLab } from '../../src/ui/useLab'
import { messages } from '../../src/ui/i18n'
import * as exporter from '../../src/ui/export'
const wrappers: ReturnType<typeof mount>[] = []
function app() { const wrapper = mount(App); wrappers.push(wrapper); return wrapper }
beforeEach(() => { localStorage.clear(); document.documentElement.dataset.theme = 'system' })
afterEach(() => { wrappers.forEach(wrapper => wrapper.unmount()); wrappers.length = 0; vi.restoreAllMocks() })
describe('complete architecture workbench', () => {
  it('starts with a readable graph, constraints, empty trace and official sources', () => {
    const wrapper = app()
    expect(wrapper.find('h1').text()).toBe(messages.en.title)
    expect(wrapper.find('.reference-section').attributes('aria-label')).toBe(messages.en.how)
    expect(wrapper.findAll('.workflow-node').length).toBeGreaterThan(3)
    expect(wrapper.find('.trace-empty').exists()).toBe(true)
    expect(wrapper.find('.storage-notice').exists()).toBe(false)
    expect(wrapper.findAll('#sources a')).toHaveLength(5)
    expect(wrapper.find('.skip-link').attributes('href')).toBe('#workbench')
  })
  it('updates every constraint, branches, recommendation and safely resets state', async () => {
    const wrapper = app()
    await wrapper.get('input[name=taskShape][value=open]').setValue()
    expect(wrapper.find('.pattern-name').text()).toBe('Orchestration blueprint')
    await wrapper.get('input[name=taskShape][value=fixed]').setValue()
    await wrapper.get('#parallel').setValue(true)
    expect(wrapper.find('.pattern-name').text()).toBe('Parallel fan-out workflow')
    expect(wrapper.findAll('.workflow-row.parallel .workflow-node')).toHaveLength(2)
    await wrapper.get('#retrieval').setValue(false)
    expect(wrapper.find('[data-node=retrieve]').exists()).toBe(false)
    await wrapper.get('#resumable').setValue(false)
    expect(wrapper.find('[data-node=checkpoint]').exists()).toBe(false)
    await wrapper.get('input[name=sideEffects][value=reversible]').setValue()
    expect(wrapper.find('[data-node=action]').text()).toBe('Reversible action')
    await wrapper.get('input[name=sideEffects][value=irreversible]').setValue()
    expect(wrapper.find('[data-node=approval]').exists()).toBe(true)
    for (const budget of [0, 1, 2, 3]) await wrapper.get(`input[name=maxRetries][value="${budget}"]`).setValue()
    expect(JSON.parse(localStorage.getItem(INPUT_KEY)!).input.maxRetries).toBe(3)
    await wrapper.get('.run-button').trigger('click')
    expect(wrapper.find('.trace').exists()).toBe(true)
    await wrapper.get('.text-button').trigger('click')
    expect(wrapper.find('.trace').exists()).toBe(false)
    expect(wrapper.text()).toContain(messages.en.resetDone)
    expect(JSON.parse(localStorage.getItem(INPUT_KEY)!).input).toEqual(DEFAULT_INPUT)
  })
  it('runs every fault, displays stopping and approval boundaries and invalidates stale traces', async () => {
    const wrapper = app()
    await wrapper.get('#fault').setValue('none')
    await wrapper.get('.run-button').trigger('click')
    expect(wrapper.find('.outcome').text()).toBe('Completed')
    expect(wrapper.find('.checkpoint-note').exists()).toBe(DEFAULT_INPUT.resumable)
    await wrapper.get('#fault').setValue('timeout')
    expect(wrapper.find('.trace').exists()).toBe(false)
    await wrapper.get('.run-button').trigger('click')
    expect(wrapper.find('.outcome').text()).toBe('Stopped safely')
    expect(wrapper.findAll('.trace-failed')).toHaveLength(1)
    expect(wrapper.findAll('.trace-skipped').length).toBeGreaterThan(0)
    await wrapper.get('#fault').setValue('invalid_output')
    await wrapper.get('.run-button').trigger('click')
    expect(wrapper.find('.trace').text()).toContain('Invalid output')
    await wrapper.get('input[name=sideEffects][value=irreversible]').setValue()
    await wrapper.get('#resumable').setValue(true)
    await wrapper.get('#fault').setValue('approval_denied')
    await wrapper.get('.run-button').trigger('click')
    expect(wrapper.find('.outcome').text()).toBe('Approval blocked')
    expect(wrapper.find('.checkpoint-note').exists()).toBe(true)
    await wrapper.get('input[name=sideEffects][value=none]').setValue()
    await wrapper.get('.run-button').trigger('click')
    expect(wrapper.find('.trace').text()).toContain('fault not applied')
    await wrapper.get('#parallel').setValue(true)
    expect(wrapper.find('.trace').exists()).toBe(false)
    expect(wrapper.text()).toContain(messages.en.changed)
  })
  it('switches and persists both languages and all three themes', async () => {
    const wrapper = app()
    await wrapper.get('button[lang="zh-CN"]').trigger('click')
    expect(wrapper.find('h1').text()).toBe(messages.zh.title)
    expect(wrapper.find('.reference-section').attributes('aria-label')).toBe(messages.zh.how)
    expect(document.documentElement.lang).toBe('zh-CN')
    for (const theme of ['dark', 'light', 'system']) {
      await wrapper.get('[data-testid=theme]').setValue(theme)
      expect(document.documentElement.dataset.theme).toBe(theme)
    }
    expect(JSON.parse(localStorage.getItem(PREFS_KEY)!)).toEqual({ locale: 'zh', theme: 'system' })
    await wrapper.get('button[lang=en]').trigger('click')
    expect(document.documentElement.lang).toBe('en')
  })
  it('restores valid settings, warns on corruption and preserves unsafe-storage usability', async () => {
    localStorage.setItem(INPUT_KEY, serializeLabInput({ ...DEFAULT_INPUT, taskShape: 'open' }))
    localStorage.setItem(PREFS_KEY, '{"locale":"zh","theme":"dark"}')
    const restored = app()
    expect(restored.find('.pattern-name').text()).toBe('任务编排蓝图')
    expect(document.documentElement.dataset.theme).toBe('dark')
    localStorage.clear(); localStorage.setItem(INPUT_KEY, '{corrupt')
    const corrupt = app()
    expect(corrupt.find('.storage-notice').text()).toBe(messages.en.savedInvalid)
    await corrupt.get('.text-button').trigger('click')
    expect(corrupt.find('.storage-notice').exists()).toBe(false)
    vi.spyOn(window.localStorage, 'getItem').mockImplementation(() => { throw new Error('denied') })
    vi.spyOn(window.localStorage, 'setItem').mockImplementation(() => { throw new Error('quota') })
    const denied = app()
    expect(denied.find('.storage-notice').text()).toBe(messages.en.storageUnavailable)
    await denied.get('button[lang="zh-CN"]').trigger('click')
    await denied.get('#parallel').setValue(true)
    expect(denied.find('.storage-notice').text()).toBe(messages.zh.storageUnavailable)
    await denied.get('.run-button').trigger('click')
    expect(denied.find('.trace').exists()).toBe(true)
  })
  it('downloads the current plan and shows a visible retryable error on failure', async () => {
    const download = vi.spyOn(exporter, 'downloadPlan').mockImplementation(() => {})
    const wrapper = app()
    await wrapper.get('.export-button').trigger('click')
    expect(download).toHaveBeenCalledOnce()
    expect(wrapper.find('.action-notice').text()).toBe(messages.en.exported)
    download.mockImplementation(() => { throw new Error('blocked') })
    await wrapper.get('.export-button').trigger('click')
    expect(wrapper.find('.action-notice').text()).toBe(messages.en.exportFailed)
  })
  it('supports direct composable updates and preference failure without corrupting state', async () => {
    const storage = { getItem: () => null, setItem: () => { throw new Error('quota') } }
    const state = useLab(storage)
    state.locale.value = 'zh'
    await nextTick()
    expect(state.storageState.value).toBe('unavailable')
    state.updateInput({ ...DEFAULT_INPUT, maxRetries: 0 })
    expect(state.input.value.maxRetries).toBe(0)
    state.run()
    expect(state.result.value?.finalState).toBe('failed')
  })
  it('renders icon defaults and named icons', () => {
    const icon = mount(AppIcon)
    expect(icon.find('svg').attributes('width')).toBe('20')
    expect(icon.find('path').attributes('d')).toContain('M9 3')
    icon.unmount()
  })
})
